version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      TZ: "Asia/Tokyo"
    command: /bin/sh -c "python /app/root.py"